#!/bin/sh -e

case "$1" in
    configure)
        if which systemctl >/dev/null 2>&1; then
            systemctl restart zabbix-agent || true
        elif which invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d zabbix-agent stop || true
            invoke-rc.d zabbix-agent start || true
        else
            /etc/init.d/zabbix-agent stop || true
            /etc/init.d/zabbix-agent start || true
        fi
    ;;
    abort-upgrade|abort-deconfigure|abort-remove)
    ;;
    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
    ;;
esac

exit 0
